def parseJsonText(String jsonText) {
  final slurper = new groovy.json.JsonSlurper()
  return new HashMap<>(slurper.parseText(jsonText))
}

podTemplate(label: 'nhf',containers: [
    containerTemplate(name: 'python', image: 'registry-vpc.cn-hangzhou.aliyuncs.com/luozixuan/python:latest', ttyEnabled: true, command: 'cat'),
    containerTemplate(
            name: 'jnlp',
            image: 'registry-vpc.cn-hangzhou.aliyuncs.com/nanhangfei/jnlp-slave:3.7-1-alpine',
            args: '${computer.jnlpmac} ${computer.name}',
            command: ''
    )
  ])
{
node ('nhf') {

    echo 'ready go'

    stage("clone code"){
        git credentialsId: '434aa890-ec99-4dd4-93ea-686fb6c3a3d2', url: 'https://github.com/luozixuan123/python-test.git'
        echo 'clone code complete'
    }
    def configFile = readFile("./.jenkins/config.json")
    # def configStates = parseJsonText(configFile)
    def slurper = new groovy.json.JsonSlurper()
    def configStates = slurper.parseText(configFile)

    stage("python test"){

        stage("start check code"){
            def sonarhome = tool name: 'sonarqube scanner 3.0.3', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
            def status = sh sonarhome + '/bin/sonar-scanner -Dsonar.host.url='+configStates.sonarHostUrl+' -Dsonar.projectName='+configStates.projectName+' -Dsonar.projectVersion='+configStates.projectVersion+' -Dsonar.projectKey='+configStates.projectName+' -Dsonar.sources=. -X'
            echo 'start check code complete'
        }

        container('python'){
            stage("unit test"){
                sh 'pytest --junitxml=./python_test/.jenkins/pytest_report.xml'
                echo 'unit test complete'
            }

            stage("run py"){
                if (configStates.mainDir != ""){
                    sh 'python ' + configStates.mainDir
                }
                echo 'run py complete'
            }

            stage("get check report"){
                sh 'curl -o sonar_report.txt'+ ' ' +configStates.sonarHostUrl+'/api/qualitygates/project_status?projectKey='+configStates.projectName
                def jsonPayload = readFile 'sonar_report.txt'
                def states = parseJsonText(jsonPayload)
                if (states.projectStatus.status == 'OK'){
                    echo 'pass sonarqube code check'
                }else {
                    echo 'fail sonarqube code check'
                    error 'sonarqube check fail'
                }
                echo 'get check report complete'
            }

        }
    }

    stage("depoly"){
        // ssh
        echo 'deploy complete'
    }

    stage('park code'){
        sh 'tar -zcvf code.tar.gz ' + configStates.projectName
        echo 'park code complete'
    }

    stage('push test report'){
        junit allowEmptyResults: true, testResults: 'unittest_report.xml'
        echo 'push test report complete'
    }

    stage('archive artifacts'){
        archiveArtifacts 'code.tar.gz'
        echo 'archive artifacts complete'
    }
}
}